### ISSUE TITLE
docs not rendered completely

### ISSUE THREAD

**Issue by dbarrosop** [inancgumus/godocc#1]
Hello,
just saw this on twitter and decided to give it a go. I tried rendering some documents and `godocc` seems to be failing to render documents completely. For instance:

```
$ godoc context | wc -l
227
$ godocc context | wc -l
54
```

Is that expected?

Thanks and great work :)
David

**Comment by inancgumus** [comment]
Hi David, thanks:)

It's because godocc is a wrapper around `go doc` — not `godoc`, they are different commands.

```bash
$ godoc context | wc -l
227
$ go doc context | wc -l
54
$ godocc context | wc -l
54
```
